# Generated by Django 4.2.4 on 2023-08-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('desc', models.CharField()),
                ('date', models.DateField()),
                ('article_type', models.CharField(max_length=50)),
                ('small_image', models.ImageField(upload_to='images_art/')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=130)),
                ('email', models.CharField(max_length=130)),
                ('message', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='SlidingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
