# Generated by Django 4.2.4 on 2023-08-16 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
