# Generated by Django 4.2.4 on 2023-08-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_delete_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField()),
                ('desc', models.CharField()),
                ('date', models.DateField()),
                ('article_type', models.CharField(max_length=50)),
                ('small_image', models.ImageField(upload_to='images_art/')),
                ('file', models.FileField(upload_to='files')),
            ],
        ),
    ]
